[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "google_stopwatch"
version = "0.0.1"
authors = [{ name = "Rafay Khan" }]
maintainers = [{ name = "Rafay Khan" }]
description = "A stopwatch program that automatically logs sessions to Google Calendar."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "pyyaml",
]

[project.optional-dependencies]
development = ["black", "ruff", "pytype"]

[tool.ruff]
# Adjust line-length to match black formatter
line-length = 88
select = [
    "A",   # flake8-builtins
    "BLE", # flake8-blind-except
    "C4",  # flake8-comprehensions
    "C90", # mccabe
    "COM", # flake8-commas
    "E",   # pycodestyle
    "EM",  # flake8-errmsg
    "W",   # pycodestyle
    "F",   # pyflakes
    "FBT", # flake8-boolean-trap
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "D",   # pydocstyle
    "ANN", # flake8-annotations
    "Q",   # flake8-quotes
    "RET", # flake8-return
    "I",   # isort
    "N",   # pep8-naming
]
include = ["*.py", "*.ipynb", "**/pyproject.toml"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
