version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%m/%d/%Y %I:%M:%S %p'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  ADTHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: ../logs/ADTs.log
    maxBytes: 524288 #.5MB
    backupCount: 3
    encoding: utf8
loggers:
  run:
    level: DEBUG
    handlers: [console]
    propagate: no
  ADTs:
    level: DEBUG
    handlers: [ADTHandler]
    propagate: no
root:
  level: DEBUG
  handlers: [console]